### ISSUE TITLE
Dart SDK version solving failed

### ISSUE THREAD

**Issue by rijazrasheed** [alextekartik/google-jsapi-picker.dart#1]
Hi,
I tried to use your plugin, but when I entered `pub get`, got an error like 
`The current Dart SDK version is 2.4.0.
Because web_first_try depends on tekartik_google_jsapi_picker from git which requires SDK version <2.0.0, version solving failed.
exit code 1`
I believe your package is not updated for Dart 2.4.0. Can you please update it ?.
Thanks.

**Comment by alextekartik** [comment]
Indeed. I have not use this for years and unfortunately it is not updated for dart 2. I tried to port it and my single test went fine if you want to try again. However I cannot offer much support on it.
